name: CI/CD
on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'develop/**'

jobs:
  Build-Verification-Test-Debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - uses: actions/checkout@v2

      - name: Lint
        run: ./gradlew lintDebug

      - name: Detekt
        run: ./gradlew detektDebug

      - name: ktlint
        run: ./gradlew ktlintCheck

      - name: Build
        run: ./gradlew assembleDebug

      - name: Test
        run: ./gradlew testDebug