name: CI/CD. Release
on:
  push:
    branches:
      - 'main'
      - 'release/**'

jobs:
  Build-Verification-Test-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - uses: actions/checkout@v2

      - name: Lint
        run: ./gradlew lintRelease

      - name: Detekt
        run: ./gradlew detekt

      - name: ktlint
        run: ./gradlew ktlintCheck

      - name: Build
        run: ./gradlew assembleRelease

      - name: Test
        run: ./gradlew testRelease