name: Debug variant
on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'develop/**'

jobs:
  setup-android-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

  prepare-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew
        with:
          cache: gradle
    needs: [ setup-android-tools ]

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew lintDebug
        with:
          cache: gradle
    needs: [ prepare-gradle ]

  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew detektDebug
        with:
          cache: gradle
    needs: [ prepare-gradle ]

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew ktlintCheck
        with:
          cache: gradle
    needs: [ prepare-gradle ]

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew assembleDebug
        with:
          cache: gradle
    needs: [ lint, detekt, ktlint ]

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew testDebug
        with:
          cache: gradle
    needs: [ build ]